#!/usr/bin/env bash
# Build holy-mountain-netlify.zip: a standalone, drag-and-drop package of the
# church site for https://app.netlify.com/drop (or `netlify deploy --dir=`).
#
# Why this is not just `zip -r` of the folder: in this repo the site lives at
# /holy-mountain/ and its redirect and header rules are scoped to that prefix
# in the repo's own netlify.toml and _headers. Dropped on Netlify the site is
# the ROOT of its own domain, so those rules would match nothing. This script
# rewrites them for "/" and ships them inside the package.
#
# Everything else is copied verbatim from holy-mountain/, so the package never
# drifts from the site: regenerate it after any change rather than editing it.
#
#   ./package.sh            # writes ../holy-mountain-netlify.zip
#
set -euo pipefail
cd "$(dirname "$0")"

SRC="$PWD"
OUT="$PWD/../holy-mountain-netlify.zip"
BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT

VIDEO="https://d8j0ntlcm91z4.cloudfront.net/user_3G9osobYr0aAENArzSDrqEFJFgW/hf_20260905_014712_4f0fe8f8-d359-462a-9690-67b6311b9e39.mp4"

# The church policy, unchanged from the repo. On its own domain there is no
# second policy to intersect with, so this is the whole of it.
CSP="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; media-src 'self'; font-src 'self'; connect-src 'self'; form-action 'self'; frame-src 'none'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; upgrade-insecure-requests"
PERMS="accelerometer=(), autoplay=(self), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), xr-spatial-tracking=()"

# ---------------------------------------------------------------- site files
echo "Collecting the site…"
cp -R "$SRC/index.html" "$SRC/assets" "$SRC/thanks" "$BUILD/"
cp "$SRC/README.md" "$SRC/fetch-video.sh" "$BUILD/"
rm -rf "$BUILD/assets/clips"          # the clip is proxied, see below
mkdir -p "$BUILD/assets/clips"

# ------------------------------------------------------------------ _headers
cat > "$BUILD/_headers" <<EOF
# Holy Mountain Washington Church — security headers.
# The page has no inline script and no style attribute, so the policy needs
# neither a hash nor 'unsafe-inline'. Keep it that way: either would be
# silently blocked in production rather than merely mis-styled.
/*
  Content-Security-Policy: $CSP
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: $PERMS
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Permitted-Cross-Domain-Policies: none
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/assets/img/*
  Cache-Control: public, max-age=604800

/assets/clips/*
  Cache-Control: public, max-age=2592000

/*.html
  Cache-Control: public, max-age=0, must-revalidate
EOF

# ---------------------------------------------------------------- _redirects
cat > "$BUILD/_redirects" <<EOF
# The animated emblem clip, proxied from this domain so the browser never
# contacts a third-party host — which media-src 'self' would refuse anyway.
# Drop a real file at assets/clips/msw-logo-8s.mp4 and it wins over this rule.
/assets/clips/msw-logo-8s.mp4  $VIDEO  200
EOF

# --------------------------------------------------------------- netlify.toml
# _headers and _redirects cover a drag-and-drop deploy. netlify.toml is what a
# CLI or Git deploy reads, so ship both and keep them saying the same thing.
cat > "$BUILD/netlify.toml" <<EOF
# Holy Mountain Washington Church — standalone Netlify site.
# Generated by holy-mountain/package.sh. Regenerate rather than hand-edit.
[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/assets/clips/msw-logo-8s.mp4"
  to = "$VIDEO"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "$CSP"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "$PERMS"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    X-Permitted-Cross-Domain-Policies = "none"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
EOF

# ------------------------------------------------------- robots and sitemap
cat > "$BUILD/robots.txt" <<'EOF'
User-agent: *
Allow: /

Sitemap: /sitemap.xml
EOF

cat > "$BUILD/sitemap.xml" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>/</loc>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
EOF

# ------------------------------------------------------------- deploy notes
cat > "$BUILD/DEPLOY.md" <<'EOF'
# Deploying this package

This folder is the whole site. It needs no build step and no dependencies.

## Drag and drop (fastest)

1. Open <https://app.netlify.com/drop>.
2. Drag this folder (or the .zip) onto the page.
3. Netlify gives you a URL straight away. Rename the site, or attach a domain,
   from **Site configuration → Domain management**.

`_headers` and `_redirects` are read automatically. `netlify.toml` says the
same thing and is what a CLI or Git deploy reads instead.

## Netlify CLI

    netlify deploy --dir=. --prod

## After the first deploy — three things

1. **Turn on form notifications.** The contact and prayer form posts to Netlify
   Forms. Go to **Forms → contact → Settings → Form notifications** and add the
   church's email, or submissions will sit in the dashboard unseen.
2. **Fill in the remaining values.** Open `assets/js/site.js` and edit the block
   at the top marked `▼▼ EDIT THIS BLOCK ▼▼`: the street address, the maps link
   and the four social profile URLs. Then set `draft: false` to remove the amber
   banner. Re-deploy.
3. **Check the hero animates.** The emblem clip is proxied from a CDN by the
   redirect rule. If it shows a still image instead of turning, run
   `./fetch-video.sh` to download the clip into `assets/clips/` and re-deploy —
   a real file there wins over the proxy.

## What is in here

- `index.html`, `thanks/` — the site and its form confirmation page
- `assets/` — stylesheet, script, self-hosted fonts, images
- `_headers`, `_redirects`, `netlify.toml` — security headers and the clip proxy
- `README.md` — how the site is put together and what the church can edit
- `fetch-video.sh` — pulls the clip in so the site depends on nothing external
EOF

# ----------------------------------------------------------------- zip it up
echo "Zipping…"
rm -f "$OUT"
( cd "$BUILD" && zip -q -r -X "$OUT" . -x '.*' )

echo
echo "Wrote $OUT"
ls -lh "$OUT" | awk '{print "  " $5}'
echo "  $(unzip -Z1 "$OUT" | wc -l) files"
