#!/usr/bin/env node
/**
 * Builds the web export, then makes it **path-independent**.
 *
 * This step is not cosmetic, and skipping it produces a blank page rather than
 * a visible error. `expo export` writes absolute URLs — `/_expo/static/js/…`,
 * `/assets/…`, `/favicon.ico` — which resolve against the *origin*, not against
 * the folder the app is served from. That is fine at a site root and broken
 * everywhere else:
 *
 *   https://host/242konnect-web/index.html  → asks for https://host/_expo/…  ✗
 *   https://rawcdn.githack.com/o/r/sha/242konnect-web/index.html
 *                                           → asks for githack.com/_expo/…   ✗
 *
 * Both are exactly how this build is shared. Rewriting the references to `./…`
 * makes them resolve against the document's own directory, which is correct at
 * a root, at a sub-path, and inside the standalone zip alike.
 *
 * It was done by hand once and lost the next time the app was rebuilt, which
 * shipped two broken preview links. Hence a script, and hence `verify-paths`
 * asserting no absolute reference survives.
 *
 * Usage:  npm run build:web -- --output-dir ../242konnect-web
 *         (any further arguments are passed through to `expo export`)
 */
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
const outIndex = args.indexOf("--output-dir");
const outDir = path.resolve(outIndex === -1 ? "dist" : args[outIndex + 1]);

console.log(`Exporting to ${outDir} …`);
execFileSync(
  "npx",
  ["expo", "export", "--platform", "web", "--clear", ...args],
  { stdio: "inherit" }
);

/** Absolute references Expo emits, and what each becomes. */
const REWRITES = [
  // index.html: the bundle and the favicon.
  [/(src|href)="\/(_expo\/|favicon)/g, '$1="./$2'],
];

const indexPath = path.join(outDir, "index.html");
let html = fs.readFileSync(indexPath, "utf8");
for (const [find, replace] of REWRITES) html = html.replace(find, replace);
fs.writeFileSync(indexPath, html);

// The bundle carries its own absolute asset URLs — fonts and images resolved
// through Expo's asset registry. Relative URLs inside JS resolve against the
// *document*, not the script, so `./assets/…` is right at every depth.
const bundles = fs
  .readdirSync(path.join(outDir, "_expo/static/js/web"))
  .filter((f) => f.endsWith(".js"));

let assetRefs = 0;
for (const file of bundles) {
  const p = path.join(outDir, "_expo/static/js/web", file);
  const js = fs.readFileSync(p, "utf8");
  const next = js.replace(/"\/assets\//g, '"./assets/');
  assetRefs += (js.match(/"\/assets\//g) || []).length;
  if (next !== js) fs.writeFileSync(p, next);
}

console.log(`Rewrote ${bundles.length} bundle(s), ${assetRefs} asset reference(s).`);

/* ------------------------------------------------------------------ *
 * The app's own deployment config.
 *
 * 242Konnect is a product, not a page on someone's consulting site. It gets
 * its own Netlify site, its own domain and its own security policy, and the
 * files that say so are emitted here so the build output is a complete,
 * self-contained site: point Netlify at this directory and it deploys, with
 * the app at `/` rather than under a path borrowed from another site.
 *
 * They are generated rather than committed because `--clear` wipes the output
 * directory on every build. A config that only survives until the next build
 * is how the absolute-path bug shipped twice.
 * ------------------------------------------------------------------ */

/** One project, not a wildcard — the app talks to Supabase and nothing else. */
const SUPABASE = "https://abdmdtftnuyjzkdkcwiq.supabase.co";

const NETLIFY_TOML = `# 242Konnect — the mobile app's web build, deployed as its own site.
#
# Generated by 242konnect-app/tools/build-web.js. Do not edit here; edit the
# script. Point a Netlify site's **base directory** at this folder and it
# serves the app at the site root.

[build]
  publish = "."
  command = ""

# A single-page app: every path renders index.html, so a deep link opens the
# app rather than a 404. Assets are matched first because they exist on disk.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # connect-src names the one Supabase project the app uses for verification
    # codes, the profiles table and the PIN function. Without it sign-up fails
    # silently: the browser blocks the request, not the server, so nothing
    # reports it.
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' ${SUPABASE}; frame-ancestors 'self';"

# Fingerprinted, so they can be cached forever. index.html cannot.
[[headers]]
  for = "/_expo/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
`;

// _headers and _redirects repeat the same rules for hosts that read those
// instead of netlify.toml — a drag-and-drop deploy at app.netlify.com/drop,
// for one, which is how the standalone zip is meant to be used.
const HEADERS = `/_expo/static/*
  Cache-Control: public, max-age=31536000, immutable
/assets/*
  Cache-Control: public, max-age=31536000, immutable
/index.html
  Cache-Control: public, max-age=0, must-revalidate

/*
  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' ${SUPABASE}; frame-ancestors 'self';
`;

const REDIRECTS = "/*  /index.html  200\n";

fs.writeFileSync(path.join(outDir, "netlify.toml"), NETLIFY_TOML);
fs.writeFileSync(path.join(outDir, "_headers"), HEADERS);
fs.writeFileSync(path.join(outDir, "_redirects"), REDIRECTS);
console.log("Wrote netlify.toml, _headers, _redirects — the output is a deployable site.");

// Fail loudly rather than shipping a build that only works at a root.
const leftover = fs.readFileSync(indexPath, "utf8").match(/(src|href)="\/[^"]*"/g);
if (leftover) {
  console.error("Absolute references survived in index.html:", leftover);
  process.exit(1);
}
console.log("Build is path-independent.");
