/**
 * Checks the two sites stay separate, and that each keeps the policy it needs.
 *
 *  - The Estevao Tati landing page (repo-root netlify.toml) publishes its own
 *    folder only, keeps its strict self-hosted CSP, and carries no 242Konnect
 *    routing, header block or Supabase exception.
 *  - 242Konnect (242konnect-web/netlify.toml, generated by build-web.js) is a
 *    site of its own: published from its own folder, allowed to reach exactly
 *    one Supabase project and no external script host.
 *
 * The landing page used to publish the repository root, so every 242Konnect
 * folder — app, prototype, API source, migrations, the zip — was served under
 * its domain. These checks are what stop that from coming back.
 *
 * Parsing the toml rather than trusting the diff: a header block that doesn't
 * match the path it's meant to is invisible until the page is live.
 */
const fs = require("fs");
const path = require("path");

const REPO = path.resolve(__dirname, "..", "..");
const read = (p) => fs.readFileSync(p, "utf8");
const landingToml = read(process.env.NETLIFY_TOML || path.join(REPO, "netlify.toml"));
const appToml = read(path.join(REPO, "242konnect-web", "netlify.toml"));

let pass = 0;
const fails = [];
const check = (label, cond) => {
  if (cond) {
    console.log("  ✓ " + label);
    pass++;
  } else {
    console.log("  ✗ " + label);
    fails.push(label);
  }
};

/** [[headers]] blocks with their `for` and CSP; comments stripped first. */
const parse = (toml) => {
  const code = toml.replace(/^\s*#.*$/gm, "");
  return {
    code,
    publish: (code.match(/publish\s*=\s*"([^"]*)"/) || [])[1],
    headers: code
      .split(/\[\[headers\]\]/)
      .slice(1)
      .map((b) => ({
        path: (b.match(/for\s*=\s*"([^"]+)"/) || [])[1],
        csp: (b.match(/Content-Security-Policy\s*=\s*"([^"]+)"/) || [])[1],
      })),
    redirects: code
      .split(/\[\[redirects\]\]/)
      .slice(1)
      .map((b) => (b.match(/from\s*=\s*"([^"]+)"/) || [])[1]),
  };
};

const landing = parse(landingToml);
const app = parse(appToml);

console.log("\n── Estevao Tati landing page ──");
const site = landing.headers.find((b) => b.path === "/*");
check("publishes its own folder, not the repository root", landing.publish === "estevao-tati-site");
check("that folder exists and holds the page", fs.existsSync(path.join(REPO, "estevao-tati-site", "index.html")));
check("nothing of 242Konnect inside the published folder",
  !fs.readdirSync(path.join(REPO, "estevao-tati-site")).some((n) => /242konnect/i.test(n)));
check("no 242Konnect routing or header rule in its config", !/242konnect/i.test(landing.code));
check("landing page has a CSP", !!site?.csp);
check("landing page allows no external script host", !!site && !/script-src[^;]*https:/.test(site.csp));
check("landing page self-hosts its fonts", !!site && !/font-src[^;]*fonts\.gstatic/.test(site.csp));
check("landing page cannot reach Supabase", !!site && !/supabase/.test(site.csp));
check("no Supabase anywhere in its config", !/supabase/i.test(landing.code));
check("the background-video proxy is kept", landing.redirects.includes("/assets/clips/bg-tech.mp4"));
check("no stray _redirects/_headers at the repo root",
  !fs.existsSync(path.join(REPO, "_redirects")) && !fs.existsSync(path.join(REPO, "_headers")));

console.log("\n── 242Konnect, its own site ──");
const appCsp = app.headers.find((b) => b.path === "/*");
check("publishes its own folder", app.publish === ".");
check("serves the app at the site root (SPA redirect to /)", /from\s*=\s*"\/\*"[\s\S]*?to\s*=\s*"\/"/.test(app.code));
check("has its own CSP", !!appCsp?.csp);
check("may reach its Supabase project",
  !!appCsp && /connect-src[^;]*https:\/\/abdmdtftnuyjzkdkcwiq\.supabase\.co/.test(appCsp.csp));
check("connect-src names one host, not a wildcard", !!appCsp && !/connect-src[^;]*(\*|https:\s)/.test(appCsp.csp));
check("allows no external script host", !!appCsp && !/script-src[^;]*https:/.test(appCsp.csp));
check("mentions nothing of the landing page", !/estevao|cloudfront|bg-tech/i.test(app.code));

console.log(`\n${pass} passed, ${fails.length} failed`);
process.exit(fails.length ? 1 : 0);
